/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Isabela-Fernando' at '16/06/16 11:51' with Gradle 2.14
 *
 * @author Isabela-Fernando, @date 16/06/16 11:51
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
